#!/bin/sh

if [ "$1" = "" ] ; then
	exit 1
else
	filename="$1"
	pfad=$HOME
	ausgabe=""
	shift
	while [ "$1" != "" ] ; do
		case "$1" in
			"-p")
				shift
				pfad="$1"
				;;
			"-f")
				shift
				ausgabe="$1"
				;;
			*)
				
				exit 1;;
		esac
		shift
	done
	if [ "$ausgabe" = "" ]; then
		find $pfad -name $filename
	else
		find $pfad -name $filename 1> $ausgabe 2> $ausgabe.fehler
		grep $filename $ausgabe
	fi

fi
exit 0
