#! /bin/sh 
# Verwendung von Sonderzeichen in  -Anweisung
# im  -Muster z. T. kein normales Quoting
# Sonderzeichen ? * \ [ ] ' " ` # & ... 
echo Sonderzeichen und case-Anweisung
echo Zeichenfolge eingeben:
read in
case  "$in" in
 \?)  # \? oder [?] - ? bedeutet sonst jedes Einzelzeichen 
	echo "$in"
	echo Test1
	;;
 \*)  # \* oder [*] - * bedeutet sonst den sonst-Fall 
	echo "$in"
	echo Test2
	;;
 [)   # kein Sonderfall 
	echo "$in"
	echo Test3
	;;
  ]) 
	echo "$in"
	echo Test4
	;;
  \') 
	echo "$in"
	echo Test5
	;;
  \") 
	echo "$in"
	echo Test6
	;;
  !) 
	echo "$in"
	echo Test7
	;;
  $) 
	echo "$in"
	echo Test8
	;;
  \#) 
	echo "$in"
	echo Test9
	;; 
  \& )  # sonst wird auch Anderes falsch ! 
	echo " $in"
	echo Test10
	;;
  \`)
	echo "$in"
	echo Test11
	;;
  \\)   # 2 Backslash einzugeben
	echo "$in"
	echo Test12
	;;
  ~ ) 
	echo " $in"
	echo Test13
	;;
  [0-9])  # nur einstellige Zahlen
	echo einstellige Zahl  $in
	;;
  [0-9][0-9]) # nur zweistellige Zahlen
        echo zweistellige Zahl  $in
 	;;
  [0-9]*)
	echo Ziffer an erster Popsition  $in
	# Nicht-Ziffern erkennen
	a=`echo "$in" | grep "[^0-9]" `
	if [ "$a" != "" ] ; then
	# es sind Nicht-Ziffern enthalten
	# Ziffern herausfiltern 
	   b=`echo " $in" | sed 's/[0-9]//g'`
	   echo enthaltene Nicht-Ziffern: $b
	# Nicht-Ziffern herausfiltern
	   a=`echo " $in" | sed 's/[^0-9]//g'`
	   echo enthaltene Ziffern: $a
	else
   	   echo Es sind nur Ziffern enthalten
	fi
	;;
  *[0-9])
        echo Ziffer an letzter Position  $in
	# Ziffern erkennen
	a=`echo "$in" | grep "[0-9]"` 
	if [ "$a" != "" ] ; then
	# es sind Ziffern enthalten
	# Ziffern herausfiltern 
	   b=`echo " $in" | sed 's/[0-9]//g'`
	   echo enthaltene Nicht-Ziffern: $b
	# Nicht-Ziffern herausfiltern
	   a=`echo " $in" | sed 's/[^0-9]//g'`
	   echo enthaltene Ziffern: $a
	else
   	   echo Es sind keine Ziffern enthalten
	fi
	;;

  [a-c]) 
	echo  $in
	echo Auswahl1
	;;
  -[pP])  # Option -p oder -P
	echo  $in
	echo Auswahl2
	;;
  -*)     # Option -*
	echo "$in"
	echo Auswahl3
	;;
  ?)
	echo "$in"
	echo sonstiges Einzelzeichen
	;;
  *)    # sonstige Zeichenfolgen
	echo "$in"
	echo default
	# Ziffern erkennen
	a=`echo "$in" | grep "[0-9]"` 
	if [ "$a" != "" ] ; then
	# es sind Ziffern enthalten
	# Ziffern herausfiltern 
	   b=`echo " $in" | sed 's/[0-9]//g'`
	   echo enthaltene Nicht-Ziffern: $b
	# Nicht-Ziffern herausfiltern
	   a=`echo " $in" | sed 's/[^0-9]//g'`
	   echo enthaltene Ziffern: $a
	else
   	   echo Es sind keine Ziffern enthalten
	fi
	;;
esac


