[Preprocessing Steps]
create_mask = True
low pass filter cutoff in s = 3
fieldmap_correction = True
prefix = preproc_
debug_output = True
atlas_registration = True
low_pass = True
repetition_time = 1.0
fwhm in mm = 6
spatial_filtering = True
show_mask = True
high pass filter cutoff in s = 90
movement_correction = True
show_registration_results = True
set_repetition = True
write_logfile = True
output_directory = /home/raid1/hheinz/Leben/Praktikum/test
high_pass = True
slicetime_correction = False
temporal_filtering = True
create_mask_subject = False
create_average_mask = True
maximum number of voxel = 50000

[Registration Settings]
affine_registration = True
max_deformation in mm = 10
deformable_registration = True
ridid_registration = True
atlas template number = 0
prealing_images = True
atlas template text = T1 MNI 1mm fullbrain
output resolution = 3,3,3
interpolator function = 0
max_iterations_p1 = 500
max_iterations_p3 = 20
max_iterations_p2 = 20

